// src/constants/symptomsBySystem.js
import {
  FaBrain,
  FaHeart,
  FaLungs,
  FaStethoscope,
  FaUserMd,
  FaToilet,
  FaEye,
  FaBone,
  FaVirus,
  FaSkiing,
} from "react-icons/fa";
import { GiLiver } from "react-icons/gi";
const SYMPTOMS_BY_SYSTEM = {
  "Nervous System / Brain": {
    icon: <FaBrain className="inline mr-2" />,
    symptoms: [
      "headache",
      "dizziness",
      "depression",
      "irritability",
      "mood_swings",
      "altered_sensorium",
      "loss_of_balance",
      "spinning_movements",
      "unsteadiness",
      "weakness_of_one_body_side",
      "slurred_speech",
      "lack_of_concentration",
      "coma",
    ],
  },
  "Cardiovascular System / Heart": {
    icon: <FaHeart className="inline mr-2" />,
    symptoms: [
      "palpitations",
      "fast_heart_rate",
      "chest_pain",
      "prominent_veins_on_calf",
      "pain_during_bowel_movements",
    ],
  },
  "Respiratory System / Lungs": {
    icon: <FaLungs className="inline mr-2" />,
    symptoms: [
      "cough",
      "high_fever",
      "breathlessness",
      "phlegm",
      "mucoid_sputum",
      "rusty_sputum",
      "blood_in_sputum",
      "throat_irritation",
      "congestion",
      "runny_nose",
      "sinus_pressure",
      "cold_hands_and_feets",
    ],
  },
  "Digestive System / Stomach and Intestines": {
    icon: <FaStethoscope className="inline mr-2" />,
    symptoms: [
      "stomach_pain",
      "acidity",
      "indigestion",
      "vomiting",
      "diarrhoea",
      "constipation",
      "nausea",
      "ulcers_on_tongue",
      "loss_of_appetite",
      "abdominal_pain",
      "belly_pain",
      "dehydration",
      "passage_of_gases",
      "stomach_bleeding",
      "distention_of_abdomen",
      "pain_in_anal_region",
      "bloody_stool",
      "irritation_in_anus",
      "pain_during_bowel_movements",
    ],
  },
  "Endocrine System / Hormones & Glands": {
    icon: <FaUserMd className="inline mr-2" />,
    symptoms: [
      "weight_gain",
      "weight_loss",
      "anxiety",
      "lethargy",
      "restlessness",
      "excessive_hunger",
      "increased_appetite",
      "abnormal_menstruation",
      "polyuria",
      "enlarged_thyroid",
      "brittle_nails",
      "obesity",
      "family_history",
    ],
  },
  "Immune / Lymphatic System": {
    icon: <FaUserMd className="inline mr-2" />,
    symptoms: [
      "shivering",
      "chills",
      "malaise",
      "swollen_lymph_nodes",
      "patches_in_throat",
      "nodal_skin_eruptions",
      "continuous_sneezing",
      "joint_pain",
      "swelling_joints",
    ],
  },
  "Urinary System": {
    icon: <FaToilet className="inline mr-2" />,
    symptoms: [
      "burning_micturition",
      "spotting_urination",
      "yellow_urine",
      "dark_urine",
      "continuous_feel_of_urine",
      "bladder_discomfort",
      "foul_smell_of_urine",
    ],
  },
  "Skin, Nails & Hair": {
    icon: <FaSkiing className="inline mr-2" />,
    symptoms: [
      "itching",
      "skin_rash",
      "scurring",
      "pus_filled_pimples",
      "blackheads",
      "skin_peeling",
      "silver_like_dusting",
      "small_dents_in_nails",
      "inflammatory_nails",
      "brittle_nails",
      "red_sore_around_nose",
      "yellow_crust_ooze",
      "blister",
      "dryness_and_tingling_lips",
      "dischromic_patches",
      "red_spots_over_body",
    ],
  },
  "Eyes & Vision": {
    icon: <FaEye className="inline mr-2" />,
    symptoms: [
      "redness_of_eyes",
      "watering_from_eyes",
      "blurred_and_distorted_vision",
      "visual_disturbances",
      "pain_behind_the_eyes",
      "yellowing_of_eyes",
      "loss_of_smell",
    ],
  },
  "Bones & Muscles": {
    icon: <FaBone className="inline mr-2" />,
    symptoms: [
      "muscle_wasting",
      "muscle_pain",
      "muscle_weakness",
      "weakness_in_limbs",
      "back_pain",
      "knee_pain",
      "hip_joint_pain",
      "neck_pain",
      "cramps",
      "movement_stiffness",
      "stiff_neck",
      "swelling_joints",
      "puffy_face_and_eyes",
      "swollen_legs",
      "swollen_blood_vessels",
      "swollen_extremities",
      "painful_walking",
    ],
  },
  Liver: {
    icon: <GiLiver className="inline mr-2" />,
    symptoms: [
      "yellowish_skin",
      "acute_liver_failure",
      "fluid_overload",
      "swelling_of_stomach",
      "dark_urine",
      "yellowing_of_eyes",
      "malaise",
      "history_of_alcohol_consumption",
    ],
  },
  "Infectious / Systemic (General)": {
    icon: <FaVirus className="inline mr-2" />,
    symptoms: [
      "toxic_look_(typhos)",
      "fever",
      "red_spots_over_body",
      "internal_itching",
      "receiving_blood_transfusion",
      "receiving_unsterile_injections",
    ],
  },
};


export default SYMPTOMS_BY_SYSTEM;
